name: release

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write # Used to authenticate to PyPI via OIDC

      contents: write # Used to authenticate github release publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build .[test]

    - name: Test with pytest
      env:
        PY_COLORS: 1 # forcibly enable pytest colors
      run: pytest

    - name: Build sdist
      run: |
        git clean -fxd
        # build sdist
        make sdist

    - name: Build wheel
      run: make wheel

    - name: Output dist file info
      run: |
        sha512sum dist/*
        tar -ztf dist/*.tar.gz | sort

    - uses: actions/upload-artifact@v4
      with:
        name: results
        path: dist/*
        if-no-files-found: error
        compression-level: 0
        overwrite: true

    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/')

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.tar.gz
        fail_on_unmatched_files: true
        draft: true
