name: test

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12', '3.13', 'pypy3.11']
        experimental: [false]
        include:
          - os: ubuntu-latest
            python-version: '3.14-dev'
            experimental: true
          - os: macos-latest
            python-version: '3.12'
            experimental: false
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]" pytest-github-actions-annotate-failures

    - name: Install non-python deps
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt install lbzip2

    - name: Test with pytest
      env:
        PY_COLORS: 1 # forcibly enable pytest colors
      run: |
        pytest --cov --cov-report=term --cov-report=xml

    - name: Submit code coverage to codecov
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: psf/black@stable
